{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/inbox00/new/blob/main/1fi.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 349
        },
        "id": "-I4rX7m_Mq3H",
        "outputId": "f2178ad0-fca5-4c35-da3a-5f696eb27190"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "DirectDownloadLinkException",
          "evalue": "ERROR: 1fichier is on a limit. Please wait 1200 minute.",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mDirectDownloadLinkException\u001b[0m               Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-10-dd691f024013>\u001b[0m in \u001b[0;36m<cell line: 72>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     70\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     71\u001b[0m \u001b[0;31m# Call the fichier function with the 1Fichier link as an argument\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 72\u001b[0;31m \u001b[0mdirect_link\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfichier\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlink\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     73\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Direct Download Link:\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdirect_link\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m<ipython-input-10-dd691f024013>\u001b[0m in \u001b[0;36mfichier\u001b[0;34m(link)\u001b[0m\n\u001b[1;32m     44\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mDirectDownloadLinkException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"ERROR: 1fichier is on a limit. Please wait a few minutes/hour.\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     45\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 46\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0mDirectDownloadLinkException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"ERROR: 1fichier is on a limit. Please wait {numbers[0]} minute.\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     47\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0;34m\"protect access\"\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstr_2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlower\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     48\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mDirectDownloadLinkException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"ERROR: This link requires a password!\\n\\nThis link requires a password!\\n- Insert sign :: after the link and write the password after the sign.\\n\\nExample: https://1fichier.com/?smmtd8twfpm66awbqz04::love you\\n\\n* No spaces between the signs ::\\n* For the password, you can use a space!\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mDirectDownloadLinkException\u001b[0m: ERROR: 1fichier is on a limit. Please wait 1200 minute."
          ]
        }
      ],
      "source": [
        "import re\n",
        "import requests\n",
        "from bs4 import BeautifulSoup\n",
        "\n",
        "class DirectDownloadLinkException(Exception):\n",
        "    pass\n",
        "\n",
        "def fichier(link: str) -> str:\n",
        "    \"\"\" 1Fichier direct link generator\n",
        "    Based on https://github.com/Maujar\n",
        "    \"\"\"\n",
        "    regex = r\"^([http:\\/\\/|https:\\/\\/]+)?.*1fichier\\.com\\/\\?.+\"\n",
        "    gan = re.match(regex, link)\n",
        "    if not gan:\n",
        "        raise DirectDownloadLinkException(\"ERROR: The link you entered is wrong!\")\n",
        "    if \"::\" in link:\n",
        "        pswd = link.split(\"::\")[-1]\n",
        "        url = link.split(\"::\")[-2]\n",
        "    else:\n",
        "        pswd = None\n",
        "        url = link\n",
        "    try:\n",
        "        if pswd is None:\n",
        "            req = requests.post(url)\n",
        "        else:\n",
        "            pw = {\"pass\": pswd}\n",
        "            req = requests.post(url, data=pw)\n",
        "    except:\n",
        "        raise DirectDownloadLinkException(\"ERROR: Unable to reach 1fichier server!\")\n",
        "    if req.status_code == 404:\n",
        "        raise DirectDownloadLinkException(\"ERROR: File not found/The link you entered is wrong!\")\n",
        "    soup = BeautifulSoup(req.content, 'html.parser')\n",
        "    if soup.find(\"a\", {\"class\": \"ok btn-general btn-orange\"}) is not None:\n",
        "        dl_url = soup.find(\"a\", {\"class\": \"ok btn-general btn-orange\"})[\"href\"]\n",
        "        if dl_url is None:\n",
        "            raise DirectDownloadLinkException(\"ERROR: Unable to generate Direct Link 1fichier!\")\n",
        "        else:\n",
        "            return dl_url\n",
        "    elif len(soup.find_all(\"div\", {\"class\": \"ct_warn\"})) == 3:\n",
        "        str_2 = soup.find_all(\"div\", {\"class\": \"ct_warn\"})[-1]\n",
        "        if \"you must wait\" in str(str_2).lower():\n",
        "            numbers = [int(word) for word in str(str_2).split() if word.isdigit()]\n",
        "            if not numbers:\n",
        "                raise DirectDownloadLinkException(\"ERROR: 1fichier is on a limit. Please wait a few minutes/hour.\")\n",
        "            else:\n",
        "                raise DirectDownloadLinkException(f\"ERROR: 1fichier is on a limit. Please wait {numbers[0]} minute.\")\n",
        "        elif \"protect access\" in str(str_2).lower():\n",
        "            raise DirectDownloadLinkException(f\"ERROR: This link requires a password!\\n\\nThis link requires a password!\\n- Insert sign :: after the link and write the password after the sign.\\n\\nExample: https://1fichier.com/?smmtd8twfpm66awbqz04::love you\\n\\n* No spaces between the signs ::\\n* For the password, you can use a space!\")\n",
        "        else:\n",
        "            print(str_2)\n",
        "            raise DirectDownloadLinkException(\"ERROR: Failed to generate Direct Link from 1fichier!\")\n",
        "    elif len(soup.find_all(\"div\", {\"class\": \"ct_warn\"})) == 4:\n",
        "        str_1 = soup.find_all(\"div\", {\"class\": \"ct_warn\"})[-2]\n",
        "        str_3 = soup.find_all(\"div\", {\"class\": \"ct_warn\"})[-1]\n",
        "        if \"you must wait\" in str(str_1).lower():\n",
        "            numbers = [int(word) for word in str(str_1).split() if word.isdigit()]\n",
        "            if not numbers:\n",
        "                raise DirectDownloadLinkException(\"ERROR: 1fichier is on a limit. Please wait a few minutes/hour.\")\n",
        "            else:\n",
        "                raise DirectDownloadLinkException(f\"ERROR: 1fichier is on a limit. Please wait {numbers[0]} minute.\")\n",
        "        elif \"bad password\" in str(str_3).lower():\n",
        "            raise DirectDownloadLinkException(\"ERROR: The password you entered is wrong!\")\n",
        "        else:\n",
        "            raise DirectDownloadLinkException(\"ERROR: Error trying to generate Direct Link from 1fichier!\")\n",
        "    else:\n",
        "        raise DirectDownloadLinkException(\"ERROR: Error trying to generate Direct Link from 1fichier!\")\n",
        "\n",
        "# Paste the provided 1Fichier link into a new code cell\n",
        "link = \"https://1fichier.com/?kz2u9vjbdpkvaqh6ll2m\"\n",
        "\n",
        "# Call the fichier function with the 1Fichier link as an argument\n",
        "direct_link = fichier(link)\n",
        "print(\"Direct Download Link:\", direct_link)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh\n",
        "!chmod +x mini.sh\n",
        "!bash ./mini.sh -b -f -p /usr/local\n",
        "!conda install -q -y jupyter\n",
        "!conda install -q -y google-colab -c conda-forge\n",
        "!python -m ipykernel install --name \"py38\" --user\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "UilSHHooTqJk",
        "outputId": "dde9b52a-f759-4b88-f5b6-253321b7aea0"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--2024-02-24 18:09:49--  https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh\n",
            "Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8203, ...\n",
            "Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.\n",
            "HTTP request sent, awaiting response... 200 OK\n",
            "Length: 89817099 (86M) [application/x-sh]\n",
            "Saving to: ‘mini.sh’\n",
            "\n",
            "mini.sh             100%[===================>]  85.66M   103MB/s    in 0.8s    \n",
            "\n",
            "2024-02-24 18:09:50 (103 MB/s) - ‘mini.sh’ saved [89817099/89817099]\n",
            "\n",
            "PREFIX=/usr/local\n",
            "Unpacking payload ...\n",
            "Collecting package metadata (current_repodata.json): - \b\b\\ \b\bdone\n",
            "Solving environment: / \b\b- \b\bdone\n",
            "\n",
            "## Package Plan ##\n",
            "\n",
            "  environment location: /usr/local\n",
            "\n",
            "  added / updated specs:\n",
            "    - _libgcc_mutex==0.1=main\n",
            "    - asn1crypto==1.3.0=py38_0\n",
            "    - ca-certificates==2020.1.1=0\n",
            "    - certifi==2019.11.28=py38_0\n",
            "    - cffi==1.14.0=py38h2e261b9_0\n",
            "    - chardet==3.0.4=py38_1003\n",
            "    - conda-package-handling==1.6.0=py38h7b6447c_0\n",
            "    - conda==4.8.2=py38_0\n",
            "    - cryptography==2.8=py38h1ba5d50_0\n",
            "    - idna==2.8=py38_1000\n",
            "    - ld_impl_linux-64==2.33.1=h53a641e_7\n",
            "    - libedit==3.1.20181209=hc058e9b_0\n",
            "    - libffi==3.2.1=hd88cf55_4\n",
            "    - libgcc-ng==9.1.0=hdf63c60_0\n",
            "    - libstdcxx-ng==9.1.0=hdf63c60_0\n",
            "    - ncurses==6.2=he6710b0_0\n",
            "    - openssl==1.1.1d=h7b6447c_4\n",
            "    - pip==20.0.2=py38_1\n",
            "    - pycosat==0.6.3=py38h7b6447c_0\n",
            "    - pycparser==2.19=py_0\n",
            "    - pyopenssl==19.1.0=py38_0\n",
            "    - pysocks==1.7.1=py38_0\n",
            "    - python==3.8.1=h0371630_1\n",
            "    - readline==7.0=h7b6447c_5\n",
            "    - requests==2.22.0=py38_1\n",
            "    - ruamel_yaml==0.15.87=py38h7b6447c_0\n",
            "    - setuptools==45.2.0=py38_0\n",
            "    - six==1.14.0=py38_0\n",
            "    - sqlite==3.31.1=h7b6447c_0\n",
            "    - tk==8.6.8=hbc83047_0\n",
            "    - tqdm==4.42.1=py_0\n",
            "    - urllib3==1.25.8=py38_0\n",
            "    - wheel==0.34.2=py38_0\n",
            "    - xz==5.2.4=h14c3975_4\n",
            "    - yaml==0.1.7=had09818_2\n",
            "    - zlib==1.2.11=h7b6447c_3\n",
            "\n",
            "\n",
            "The following NEW packages will be INSTALLED:\n",
            "\n",
            "  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main\n",
            "  asn1crypto         pkgs/main/linux-64::asn1crypto-1.3.0-py38_0\n",
            "  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0\n",
            "  certifi            pkgs/main/linux-64::certifi-2019.11.28-py38_0\n",
            "  cffi               pkgs/main/linux-64::cffi-1.14.0-py38h2e261b9_0\n",
            "  chardet            pkgs/main/linux-64::chardet-3.0.4-py38_1003\n",
            "  conda              pkgs/main/linux-64::conda-4.8.2-py38_0\n",
            "  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.6.0-py38h7b6447c_0\n",
            "  cryptography       pkgs/main/linux-64::cryptography-2.8-py38h1ba5d50_0\n",
            "  idna               pkgs/main/linux-64::idna-2.8-py38_1000\n",
            "  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7\n",
            "  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0\n",
            "  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4\n",
            "  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0\n",
            "  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0\n",
            "  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_0\n",
            "  openssl            pkgs/main/linux-64::openssl-1.1.1d-h7b6447c_4\n",
            "  pip                pkgs/main/linux-64::pip-20.0.2-py38_1\n",
            "  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py38h7b6447c_0\n",
            "  pycparser          pkgs/main/noarch::pycparser-2.19-py_0\n",
            "  pyopenssl          pkgs/main/linux-64::pyopenssl-19.1.0-py38_0\n",
            "  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py38_0\n",
            "  python             pkgs/main/linux-64::python-3.8.1-h0371630_1\n",
            "  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5\n",
            "  requests           pkgs/main/linux-64::requests-2.22.0-py38_1\n",
            "  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.87-py38h7b6447c_0\n",
            "  setuptools         pkgs/main/linux-64::setuptools-45.2.0-py38_0\n",
            "  six                pkgs/main/linux-64::six-1.14.0-py38_0\n",
            "  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h7b6447c_0\n",
            "  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0\n",
            "  tqdm               pkgs/main/noarch::tqdm-4.42.1-py_0\n",
            "  urllib3            pkgs/main/linux-64::urllib3-1.25.8-py38_0\n",
            "  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0\n",
            "  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4\n",
            "  yaml               pkgs/main/linux-64::yaml-0.1.7-had09818_2\n",
            "  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3\n",
            "\n",
            "\n",
            "Preparing transaction: | \b\b/ \b\b- \b\b\\ \b\bdone\n",
            "Executing transaction: / \b\b- \b\b\\ \b\b| \b\b/ \b\b- \b\b\\ \b\b| \b\b/ \b\b- \b\b\\ \b\b| \b\b/ \b\b- \b\b\\ \b\b| \b\b/ \b\b- \b\b\\ \b\b| \b\b/ \b\b- \b\bdone\n",
            "installation finished.\n",
            "WARNING:\n",
            "    You currently have a PYTHONPATH environment variable set. This may cause\n",
            "    unexpected behavior when running the Python interpreter in Miniconda3.\n",
            "    For best results, please verify that your PYTHONPATH only points to\n",
            "    directories of packages that are compatible with the Python interpreter\n",
            "    in Miniconda3: /usr/local\n",
            "Collecting package metadata (current_repodata.json): ...working... done\n",
            "Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.\n",
            "Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/cli/install.py\", line 261, in install\n",
            "    unlink_link_transaction = solver.solve_for_transaction(\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 114, in solve_for_transaction\n",
            "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 157, in solve_for_diff\n",
            "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 281, in solve_final_state\n",
            "    ssc = self._run_sat(ssc)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/common/io.py\", line 88, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 805, in _run_sat\n",
            "    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/common/io.py\", line 88, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/resolve.py\", line 1316, in solve\n",
            "    raise UnsatisfiableError({})\n",
            "conda.exceptions.UnsatisfiableError: \n",
            "Did not find conflicting dependencies. If you would like to know which\n",
            "packages conflict ensure that you have enabled unsatisfiable hints.\n",
            "\n",
            "conda config --set unsatisfiable_hints True\n",
            "            \n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/exceptions.py\", line 1079, in __call__\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/cli/main.py\", line 84, in _main\n",
            "    exit_code = do_call(args, p)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/cli/conda_argparse.py\", line 82, in do_call\n",
            "    return getattr(module, func_name)(args, parser)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/cli/main_install.py\", line 20, in execute\n",
            "    install(args, parser, 'install')\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/cli/install.py\", line 295, in install\n",
            "    unlink_link_transaction = solver.solve_for_transaction(\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 114, in solve_for_transaction\n",
            "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 157, in solve_for_diff\n",
            "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 281, in solve_final_state\n",
            "    ssc = self._run_sat(ssc)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/common/io.py\", line 88, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/core/solve.py\", line 751, in _run_sat\n",
            "    conflicting_specs = set(ssc.r.get_conflicting_specs(tuple(final_environment_specs),\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/resolve.py\", line 1105, in get_conflicting_specs\n",
            "    C = r2.gen_clauses()\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/common/io.py\", line 88, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/resolve.py\", line 911, in gen_clauses\n",
            "    C.Require(C.Or, nkey, self.push_MatchSpec(C, ms))\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/resolve.py\", line 854, in push_MatchSpec\n",
            "    sat_name = self.to_sat_name(spec)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/resolve.py\", line 844, in to_sat_name\n",
            "    return '@s@' + text_type(val) + ('?' if val.optional else '')\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/models/match_spec.py\", line 301, in __str__\n",
            "    builder.append(('::%s' if builder else '%s') % name_matcher)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/models/match_spec.py\", line 770, in __str__\n",
            "    return self._raw_value\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/conda\", line 13, in <module>\n",
            "    sys.exit(main())\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/cli/main.py\", line 150, in main\n",
            "    return conda_exception_handler(_main, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/exceptions.py\", line 1371, in conda_exception_handler\n",
            "    return_value = exception_handler(func, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.8/site-packages/conda/exceptions.py\", line 1079, in __call__\n",
            "    return func(*args, **kwargs)\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "Collecting package metadata (current_repodata.json): ...working... ^C\n",
            "/usr/local/bin/python: No module named ipykernel\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import requests\n",
        "from google.colab import drive\n",
        "from concurrent.futures import ThreadPoolExecutor\n",
        "\n",
        "# Mount Google Drive\n",
        "drive.mount('/content/drive')\n",
        "\n",
        "# URL of the file to download\n",
        "url = \"https://a-13.1fichier.com/c786374113\"\n",
        "filename = \"file_from_1fichier.mp4\"\n",
        "\n",
        "# Download the file from the URL\n",
        "response = requests.get(url, stream=True)\n",
        "\n",
        "# Check if the request was successful\n",
        "if response.status_code == 200:\n",
        "    # Total size in bytes.\n",
        "    total_size = int(response.headers.get('content-length', 0))\n",
        "    block_size = 1024 * 1024 * 4 # 4 Megabyte\n",
        "\n",
        "    with open(f\"/content/drive/My Drive/{filename}\", 'wb') as f:\n",
        "        with ThreadPoolExecutor(max_workers=16) as executor:\n",
        "            futures = []\n",
        "            for data in response.iter_content(block_size):\n",
        "                future = executor.submit(f.write, data)\n",
        "                futures.append(future)\n",
        "\n",
        "            # Wait for all futures to complete\n",
        "            for future in futures:\n",
        "                future.result()\n",
        "\n",
        "                # Calculate progress percentage\n",
        "                progress = min(100, (f.tell() / total_size) * 100)\n",
        "                print(f\"Download Progress: {progress:.2f}%\", end=\"\\r\")\n",
        "\n",
        "    print(f\"\\nFile '{filename}' downloaded and saved to Google Drive successfully.\")\n",
        "else:\n",
        "    print(\"Failed to download the file.\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2amnQ3asUVB7",
        "outputId": "810e66ad-f413-4efe-b646-58c25dd90dca"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n",
            "Failed to download the file.\n"
          ]
        }
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNe18mqvkL1tA9c0JNrS5Ms",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}